service: serverless-graphql

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-plugin-tracing

custom:
  serverless-offline:
    port: 4000
  webpackIncludeModules: true

functions:
  graphql:
    handler: handler.graphqlHandler